### ISSUE TITLE
Site offline?

### ISSUE THREAD

**Issue by y-a-v-a** [libgd/website#1]
When requesting http://www.libgd.org/ I receive a GitHub 404...

<img width="427" alt="screen shot 2016-07-16 at 09 25 01" src="https://cloud.githubusercontent.com/assets/375507/16893412/39571ff4-4b37-11e6-81f3-5f923eb2ccae.png">

**Comment by cmb69** [comment]
That's a temporary DNS issue; you can use http://libgd.github.io/ in the meantime.

**Comment by vapier** [comment]
we're tracking this in https://github.com/libgd/libgd/issues/256
